package net.opendasharchive.openarchive.util

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import net.opendasharchive.openarchive.BuildConfig
import net.opendasharchive.openarchive.core.logger.AppLogger
import org.bouncycastle.asn1.ASN1ObjectIdentifier
import org.bouncycastle.asn1.x500.X500Name
import org.bouncycastle.asn1.x509.AlgorithmIdentifier
import org.bouncycastle.asn1.x509.AuthorityKeyIdentifier
import org.bouncycastle.asn1.x509.BasicConstraints
import org.bouncycastle.asn1.x509.Extension
import org.bouncycastle.asn1.x509.ExtendedKeyUsage
import org.bouncycastle.asn1.x509.KeyPurposeId
import org.bouncycastle.asn1.x509.KeyUsage
import org.bouncycastle.asn1.x509.SubjectKeyIdentifier
import org.bouncycastle.asn1.x509.SubjectPublicKeyInfo
import org.bouncycastle.cert.jcajce.JcaX509CertificateConverter
import org.bouncycastle.cert.jcajce.JcaX509v3CertificateBuilder
import org.bouncycastle.crypto.digests.SHA1Digest
import org.bouncycastle.jce.provider.BouncyCastleProvider
import org.bouncycastle.jce.spec.ECNamedCurveGenParameterSpec
import org.bouncycastle.operator.ContentSigner
import org.bouncycastle.util.io.pem.PemObject
import org.bouncycastle.util.io.pem.PemWriter
import org.contentauth.c2pa.Builder
import org.contentauth.c2pa.C2PA
import org.contentauth.c2pa.FileStream
import org.contentauth.c2pa.Reader
import org.contentauth.c2pa.Signer
import org.contentauth.c2pa.SigningAlgorithm
import java.io.ByteArrayOutputStream
import java.io.File
import java.io.StringWriter
import java.math.BigInteger
import java.security.KeyPairGenerator
import java.security.KeyStore
import java.security.PrivateKey
import java.security.PublicKey
import java.security.SecureRandom
import java.security.Security
import java.security.Signature
import java.security.cert.X509Certificate
import java.security.spec.ECGenParameterSpec
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.TimeZone
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.spec.GCMParameterSpec

object ProofmodeC2paManager {

    // EC P-256 signing key pair generated by BouncyCastle (software).
    // Private key is encrypted at rest with AES-256-GCM; the AES wrap key lives
    // in Android Keystore (TEE-backed, never exported to disk).
    // Signer.fromKeys is used because KeyStoreSigner.createSigner is broken in
    // c2pa-android 0.0.9 — consistently throws "COSE Signer does not contain
    // signing certificate" regardless of cert format.
    private const val KEY_FILE        = "c2pa_private.key"
    private const val CERT_CHAIN_FILE = "c2pa_cert_chain.pem"
    private const val CA_CERT_FILE    = "c2pa_ca_cert.pem"
    private const val WRAP_KEY_ALIAS  = "openarchive_c2pa_wrap_key"
    private const val KEYSTORE_PROVIDER = "AndroidKeyStore"
    private const val AES_GCM_TRANSFORM = "AES/GCM/NoPadding"
    private const val GCM_TAG_LEN = 128

    @Volatile private var trustSettingsLoaded = false

    private val isoFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'", Locale.US).apply {
        timeZone = TimeZone.getTimeZone("UTC")
    }

    fun init(context: Context) {
        try {
            Security.removeProvider(BouncyCastleProvider.PROVIDER_NAME)
            Security.insertProviderAt(BouncyCastleProvider(), 1)
            trustSettingsLoaded = false
            ensureCertsExist(context)
            AppLogger.i("[C2PA] ProofmodeC2paManager initialized")
        } catch (e: Exception) {
            AppLogger.e("[C2PA] Initialization failed", e)
        }
    }

    suspend fun embedProof(
        file: File,
        mimeType: String,
        metadata: MetadataCollector.CaptureMetadata,
        context: Context,
    ): File? {
        if (!Prefs.useC2pa) return null
        if (!file.exists()) {
            AppLogger.e("[C2PA] File does not exist: ${file.absolutePath}")
            return null
        }

        return try {
            val privateKeyPem = loadKeyPem(context) ?: run {
                ensureCertsExist(context)
                loadKeyPem(context) ?: return null
            }
            val certChainPem = loadPlain(context, CERT_CHAIN_FILE) ?: run {
                ensureCertsExist(context)
                loadPlain(context, CERT_CHAIN_FILE) ?: return null
            }
            val caCertPem = loadPlain(context, CA_CERT_FILE) ?: run {
                ensureCertsExist(context)
                loadPlain(context, CA_CERT_FILE) ?: return null
            }

            if (!trustSettingsLoaded) {
                try {
                    C2PA.loadSettings(buildTrustSettings(caCertPem), "json")
                    trustSettingsLoaded = true
                } catch (e: Exception) {
                    AppLogger.w("[C2PA] loadSettings warning: ${e.message}")
                }
            }

            val manifestJson = buildManifestJson(metadata)

            val tmp = File(file.parent, "${file.nameWithoutExtension}_c2pa_tmp.${file.extension}")
            tmp.delete()

            // Signer.fromKeys — proven working in c2pa-android 0.0.9.
            // FileStream source + dest: full file never loaded into RAM.
            Builder.fromJson(manifestJson).use { builder ->
                Signer.fromKeys(certChainPem, privateKeyPem, SigningAlgorithm.ES256).use { signer ->
                    FileStream(file, FileStream.Mode.READ, false).use { source ->
                        FileStream(tmp, FileStream.Mode.READ_WRITE, true).use { dest ->
                            builder.sign(mimeType, source, dest, signer)
                        }
                    }
                }
            }

            val verified = try {
                FileStream(tmp, FileStream.Mode.READ, false).use { s ->
                    Reader.fromStream(mimeType, s).use { it.isEmbedded() }
                }
            } catch (e: Exception) {
                AppLogger.e("[C2PA] Post-sign verification threw: ${e.message}")
                tmp.delete()
                false
            }
            if (!verified) {
                AppLogger.e("[C2PA] Post-sign verification failed — original preserved: ${file.name}")
                tmp.delete()
                return null
            }

            if (!tmp.renameTo(file)) {
                file.delete()
                tmp.renameTo(file)
            }

            AppLogger.i("[C2PA] Manifest embedded + verified: ${file.name} (${file.length() / 1024} KB)")
            file
        } catch (e: Exception) {
            AppLogger.e("[C2PA] Failed to embed proof in ${file.name}", e)
            null
        }
    }

    // ---------------------------------------------------------------------------
    // Key + cert generation — software EC key, Keystore-wrapped at rest
    // ---------------------------------------------------------------------------

    private fun ensureCertsExist(context: Context) {
        val keyFile   = File(context.filesDir, KEY_FILE)
        val chainFile = File(context.filesDir, CERT_CHAIN_FILE)
        val caFile    = File(context.filesDir, CA_CERT_FILE)
        if (keyFile.exists() && chainFile.exists() && caFile.exists()) {
            // Verify encrypted key is still readable (detects Keystore wrap-key loss)
            if (loadKeyPem(context) != null) return
            AppLogger.w("[C2PA] Wrap key lost — wiping cert files and regenerating")
            keyFile.delete(); chainFile.delete(); caFile.delete()
        }

        AppLogger.i("[C2PA] Generating EC P-256 key pair + cert chain")

        val kpg = KeyPairGenerator.getInstance("EC", BouncyCastleProvider.PROVIDER_NAME)
        kpg.initialize(ECNamedCurveGenParameterSpec("secp256r1"))
        val keyPair = kpg.generateKeyPair()

        val caCert   = buildCaCert(keyPair.private, keyPair.public)
        val leafCert = buildLeafCert(keyPair.private, keyPair.public, caCert)

        val chainPem     = toPem("CERTIFICATE", leafCert.encoded) + toPem("CERTIFICATE", caCert.encoded)
        val caCertPem    = toPem("CERTIFICATE", caCert.encoded)
        val privateKeyPem = toPem("PRIVATE KEY", keyPair.private.encoded)

        // Atomic write via tmp → rename
        val tmpKey   = File(context.filesDir, "$KEY_FILE.tmp")
        val tmpChain = File(context.filesDir, "$CERT_CHAIN_FILE.tmp")
        val tmpCa    = File(context.filesDir, "$CA_CERT_FILE.tmp")
        try {
            writeEncrypted(tmpKey, privateKeyPem.toByteArray(Charsets.UTF_8))
            tmpChain.writeText(chainPem)
            tmpCa.writeText(caCertPem)
            tmpKey.renameTo(keyFile)
            tmpChain.renameTo(chainFile)
            tmpCa.renameTo(caFile)
        } catch (e: Exception) {
            tmpKey.delete(); tmpChain.delete(); tmpCa.delete()
            throw e
        }

        trustSettingsLoaded = false
        AppLogger.i("[C2PA] Key + cert chain written")
    }

    private fun loadKeyPem(context: Context): String? {
        val f = File(context.filesDir, KEY_FILE)
        if (!f.exists()) return null
        return readEncrypted(f)?.toString(Charsets.UTF_8)
    }

    private fun loadPlain(context: Context, name: String): String? {
        val f = File(context.filesDir, name)
        return if (f.exists()) f.readText() else null
    }

    // ---------------------------------------------------------------------------
    // AES-256-GCM wrap for private key file
    // ---------------------------------------------------------------------------

    private fun ensureWrapKey() {
        val ks = KeyStore.getInstance(KEYSTORE_PROVIDER).also { it.load(null) }
        if (ks.containsAlias(WRAP_KEY_ALIAS)) return
        val spec = KeyGenParameterSpec.Builder(
            WRAP_KEY_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(256)
            .build()
        KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE_PROVIDER)
            .also { it.init(spec) }
            .generateKey()
    }

    private fun writeEncrypted(file: File, plaintext: ByteArray) {
        ensureWrapKey()
        val ks  = KeyStore.getInstance(KEYSTORE_PROVIDER).also { it.load(null) }
        val key = ks.getKey(WRAP_KEY_ALIAS, null) as javax.crypto.SecretKey
        val cipher = Cipher.getInstance(AES_GCM_TRANSFORM)
        cipher.init(Cipher.ENCRYPT_MODE, key)
        val iv         = cipher.iv
        val ciphertext = cipher.doFinal(plaintext)
        file.outputStream().use { out ->
            out.write(iv.size.to4Bytes())
            out.write(iv)
            out.write(ciphertext)
        }
    }

    private fun readEncrypted(file: File): ByteArray? = try {
        ensureWrapKey()
        val ks  = KeyStore.getInstance(KEYSTORE_PROVIDER).also { it.load(null) }
        val key = ks.getKey(WRAP_KEY_ALIAS, null) as javax.crypto.SecretKey
        val bytes      = file.readBytes()
        val ivLen      = bytes.sliceArray(0..3).from4Bytes()
        val iv         = bytes.sliceArray(4 until 4 + ivLen)
        val ciphertext = bytes.sliceArray(4 + ivLen until bytes.size)
        val cipher = Cipher.getInstance(AES_GCM_TRANSFORM)
        cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_LEN, iv))
        cipher.doFinal(ciphertext)
    } catch (e: Exception) {
        AppLogger.e("[C2PA] Failed to decrypt key file", e)
        null
    }

    private fun Int.to4Bytes(): ByteArray = byteArrayOf(
        (this shr 24).toByte(), (this shr 16).toByte(), (this shr 8).toByte(), this.toByte()
    )

    private fun ByteArray.from4Bytes(): Int =
        ((this[0].toInt() and 0xFF) shl 24) or
        ((this[1].toInt() and 0xFF) shl 16) or
        ((this[2].toInt() and 0xFF) shl 8) or
        (this[3].toInt() and 0xFF)

    // ---------------------------------------------------------------------------
    // Certificate building — BouncyCastle with software key (works correctly)
    // ---------------------------------------------------------------------------

    private fun buildCaCert(privateKey: PrivateKey, publicKey: PublicKey): X509Certificate {
        val subject  = X500Name("CN=OpenArchive Save Root CA, O=OpenArchive, C=US")
        val serial   = BigInteger(64, SecureRandom())
        val notBefore = Date(System.currentTimeMillis() - 86_400_000L)
        val notAfter  = Date(System.currentTimeMillis() + 20L * 365 * 24 * 60 * 60 * 1000)
        val builder  = JcaX509v3CertificateBuilder(subject, serial, notBefore, notAfter, subject, publicKey)
        val spki = SubjectPublicKeyInfo.getInstance(publicKey.encoded)
        val ski  = computeSki(spki)
        builder.addExtension(Extension.subjectKeyIdentifier, false, SubjectKeyIdentifier(ski))
        builder.addExtension(Extension.basicConstraints, true, BasicConstraints(true))
        builder.addExtension(Extension.keyUsage, true,
            KeyUsage(KeyUsage.keyCertSign or KeyUsage.cRLSign or KeyUsage.digitalSignature))
        return JcaX509CertificateConverter()
            .setProvider(BouncyCastleProvider.PROVIDER_NAME)
            .getCertificate(builder.build(BcContentSigner(privateKey, "SHA256withECDSA")))
    }

    private fun buildLeafCert(privateKey: PrivateKey, publicKey: PublicKey, caCert: X509Certificate): X509Certificate {
        val subject   = X500Name("CN=OpenArchive Save, O=OpenArchive, C=US")
        val issuer    = X500Name("CN=OpenArchive Save Root CA, O=OpenArchive, C=US")
        val serial    = BigInteger(64, SecureRandom())
        val notBefore = Date(System.currentTimeMillis() - 86_400_000L)
        val notAfter  = Date(System.currentTimeMillis() + 10L * 365 * 24 * 60 * 60 * 1000)
        val builder   = JcaX509v3CertificateBuilder(issuer, serial, notBefore, notAfter, subject, publicKey)
        val spki  = SubjectPublicKeyInfo.getInstance(publicKey.encoded)
        val ski   = computeSki(spki)
        val caSki = computeSki(SubjectPublicKeyInfo.getInstance(caCert.publicKey.encoded))
        builder.addExtension(Extension.subjectKeyIdentifier, false, SubjectKeyIdentifier(ski))
        builder.addExtension(Extension.authorityKeyIdentifier, false, AuthorityKeyIdentifier(caSki))
        builder.addExtension(Extension.basicConstraints, true, BasicConstraints(false))
        builder.addExtension(Extension.keyUsage, true,
            KeyUsage(KeyUsage.digitalSignature or KeyUsage.nonRepudiation))
        // id-kp-documentSigning (RFC 9336) — correct EKU for media signing certs
        builder.addExtension(Extension.extendedKeyUsage, true,
            ExtendedKeyUsage(KeyPurposeId.getInstance(ASN1ObjectIdentifier("1.3.6.1.5.5.7.3.36"))))
        return JcaX509CertificateConverter()
            .setProvider(BouncyCastleProvider.PROVIDER_NAME)
            .getCertificate(builder.build(BcContentSigner(privateKey, "SHA256withECDSA")))
    }

    private fun computeSki(spki: SubjectPublicKeyInfo): ByteArray {
        val keyBytes = spki.publicKeyData.bytes
        val digest   = SHA1Digest()
        val result   = ByteArray(digest.digestSize)
        digest.update(keyBytes, 0, keyBytes.size)
        digest.doFinal(result, 0)
        return result
    }

    private fun toPem(type: String, encoded: ByteArray): String {
        val sw = StringWriter()
        PemWriter(sw).use { it.writeObject(PemObject(type, encoded)) }
        return sw.toString()
    }

    private class BcContentSigner(
        private val privateKey: PrivateKey,
        private val algorithm: String,
    ) : ContentSigner {
        private val sig = Signature.getInstance(algorithm, BouncyCastleProvider.PROVIDER_NAME)
            .also { it.initSign(privateKey) }
        private val buf = ByteArrayOutputStream()
        override fun getAlgorithmIdentifier(): AlgorithmIdentifier =
            AlgorithmIdentifier(ASN1ObjectIdentifier("1.2.840.10045.4.3.2"))
        override fun getOutputStream(): java.io.OutputStream = buf
        override fun getSignature(): ByteArray {
            sig.update(buf.toByteArray())
            return sig.sign()
        }
    }

    // ---------------------------------------------------------------------------
    // Trust settings + manifest JSON
    // ---------------------------------------------------------------------------

    private fun buildTrustSettings(caCertPem: String): String {
        val escaped = caCertPem
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
        return """{"trust":{"trust_anchors":"$escaped"}}"""
    }

    private fun buildManifestJson(m: MetadataCollector.CaptureMetadata): String {
        val captureIso    = isoFormat.format(Date(m.captureTime))
        val claimGenerator = "OpenArchive Save/${BuildConfig.VERSION_NAME} (build ${BuildConfig.VERSION_CODE})"
        val assertions = buildList {
            add(actionsAssertion())
            add(creativeWorkAssertion(m, captureIso))
            add(deviceAssertion(m))
            if (m.latitude != null && m.longitude != null) add(locationAssertion(m))
            if (m.networkType != null || m.ipv4 != null || m.ipv6 != null || m.cellInfo != null) add(networkAssertion(m))
        }.joinToString(",\n")
        return """
        {
          "claim_generator": ${claimGenerator.toJsonString()},
          "assertions": [
            $assertions
          ]
        }
        """.trimIndent()
    }

    private fun actionsAssertion() = """
        {
          "label": "c2pa.actions",
          "data": {
            "actions": [{
              "action": "c2pa.created",
              "digitalSourceType": "http://cv.iptc.org/newscodes/digitalsourcetype/digitalCapture"
            }]
          }
        }
    """.trimIndent()

    private fun creativeWorkAssertion(m: MetadataCollector.CaptureMetadata, captureIso: String): String {
        val locationBlock = if (m.latitude != null && m.longitude != null) {
            buildString {
                append(""","locationCreated":{"@type":"Place","geo":{"@type":"GeoCoordinates","latitude":${m.latitude},"longitude":${m.longitude}""")
                if (m.locationAltitude != null) append(""","elevation":${m.locationAltitude}""")
                append("}}")
            }
        } else ""
        return """
        {
          "label": "stds.schema-org.CreativeWork",
          "data": {
            "@context": "https://schema.org",
            "@type": "CreativeWork",
            "author": [{
              "@type": "SoftwareApplication",
              "name": "OpenArchive Save",
              "version": ${BuildConfig.VERSION_NAME.toJsonString()},
              "buildNumber": "${BuildConfig.VERSION_CODE}"
            }],
            "dateCreated": "$captureIso"
            $locationBlock
          }
        }
        """.trimIndent()
    }

    private fun deviceAssertion(m: MetadataCollector.CaptureMetadata) = """
        {
          "label": "org.openarchive.save.device",
          "data": {
            "make": ${m.deviceMake.toJsonString()},
            "model": ${m.deviceModel.toJsonString()},
            "brand": ${m.deviceBrand.toJsonString()},
            "hardware": ${m.hardware.toJsonString()},
            "locale": ${m.locale.toJsonString()},
            "language": ${m.language.toJsonString()}
            ${if (m.screenSizeInches != null) ""","screenSizeInches": ${m.screenSizeInches}""" else ""}
          }
        }
    """.trimIndent()

    private fun locationAssertion(m: MetadataCollector.CaptureMetadata): String {
        val fields = buildString {
            append(""""latitude": ${m.latitude}""")
            append(""","longitude": ${m.longitude}""")
            if (m.locationAltitude != null)  append(""","altitude": ${m.locationAltitude}""")
            if (m.locationAccuracy != null)  append(""","accuracy": ${m.locationAccuracy}""")
            if (m.locationBearing != null)   append(""","bearing": ${m.locationBearing}""")
            if (m.locationSpeed != null)     append(""","speed": ${m.locationSpeed}""")
            if (m.locationProvider != null)  append(""","provider": ${m.locationProvider.toJsonString()}""")
            if (m.locationTime != null)      append(""","timestamp": ${isoFormat.format(Date(m.locationTime)).toJsonString()}""")
        }
        return """{"label":"org.openarchive.save.location","data":{$fields}}"""
    }

    private fun networkAssertion(m: MetadataCollector.CaptureMetadata): String {
        val fields = buildList {
            if (m.networkType != null) add(""""networkType": ${m.networkType.toJsonString()}""")
            if (m.ipv4 != null)        add(""""ipv4": ${m.ipv4.toJsonString()}""")
            if (m.ipv6 != null)        add(""""ipv6": ${m.ipv6.toJsonString()}""")
            if (m.cellInfo != null)    add(""""cellInfo": ${m.cellInfo}""")
        }.joinToString(",")
        return """{"label":"org.openarchive.save.network","data":{$fields}}"""
    }

    private fun String.toJsonString(): String {
        val escaped = replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t")
        return "\"$escaped\""
    }
}
